manifest:
  remotes:
    - name: zmkfirmware
      url: https://github.com/zmkfirmware/zmk
    - name: urob
      url: https://github.com/urob/zmk
  projects:
    - name: zmk
      remote: urob
      revision: v3.5
      import: app/west.yml
  self:
    path: config