manifest:
  remotes:
    - name: zmkfirmware
      url: https://github.com/zmkfirmware/zmk
    - name: ftas
      url: https://github.com/ftas/zmk
  projects:
    - name: zmk
      remote: ftas
      revision: mouse-fix
      import: app/west.yml
  self:
    path: config