manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ftas
      url-base: https://github.com/ftas
  projects:
    - name: zmk
      remote: ftas
      revision: mouse-fix
      import: app/west.yml
  self:
    path: config